### ISSUE TITLE
etcd service is failing to start

### ISSUE THREAD

**Issue by pradvara** [contiv/ansible#213] opened 2016-06-01 14:30 UTC
May 31 16:08:49 vm11 clusterm: level=info msg="TASK [ucp : download and install ucp images] ***********************************"
May 31 16:08:49 vm11 systemd: etcd.service holdoff time over, scheduling restart.
May 31 16:08:49 vm11 systemd: Started Etcd.
May 31 16:08:49 vm11 systemd: Starting Etcd...
May 31 16:08:49 vm11 etcd.sh: + case $1 in
May 31 16:08:49 vm11 etcd.sh: + '[' '!' -f /tmp/etcd.existing ']'
May 31 16:08:49 vm11 etcd.sh: + echo '==> no peer found or single member cluster at time of commission, failing now'
May 31 16:08:49 vm11 etcd.sh: ==> no peer found or single member cluster at time of commission, failing now
May 31 16:08:49 vm11 etcd.sh: + exit 1
May 31 16:08:49 vm11 systemd: etcd.service: main process exited, code=exited, status=1/FAILURE
May 31 16:08:49 vm11 etcd.sh: + case $1 in
May 31 16:08:49 vm11 etcd.sh: + echo '==> no peer found or single member cluster at time of commission'
May 31 16:08:49 vm11 etcd.sh: ==> no peer found or single member cluster at time of commission
May 31 16:08:49 vm11 etcd.sh: + exit 1
May 31 16:08:49 vm11 systemd: etcd.service: control process exited, code=exited status=1
May 31 16:08:49 vm11 systemd: Unit etcd.service entered failed state.
May 31 16:08:49 vm11 systemd: etcd.service failed.
May 31 16:08:49 vm11 systemd: etcd.service holdoff time over, scheduling restart.

**Comment by vvb** [comment] 2016-06-01 14:31
sure..

**Comment by vvb** [comment] 2016-06-01 14:34
@mapuri @pradvara I can think of a fix for this.. will submit a patch in some time..
root cause is really, that `docker run` fails(because of network issues) so the service fails, but we have created `/tmp/etcd.existing`. so, when you retry it will always error out.

**Comment by vvb** [comment] 2016-06-01 14:43
I haven't tested this patch yet, but I think this should work. essentially moving the creation of `/tmp/etcd.existing` to the bottom; after `docker run`. so if, `docker run` fails, `/tmp/etcd.existing` will not be created. 

```
diff --git a/roles/etcd/templates/etcd.j2 b/roles/etcd/templates/etcd.j2
index 0368882..794dcb9 100644
--- a/roles/etcd/templates/etcd.j2
+++ b/roles/etcd/templates/etcd.j2
@@ -83,7 +83,6 @@ http://{{ addr }}:{{ etcd_client_port1 }},http://{{ addr }}:{{ etcd_client_port2
 {#- if you change the indentation below, make sure the generated file stays readable -#}
     # on master nodes, if the cluster is being initialized for first time then initialize it
     if [ ! -f {{ etcd_tmp_filename }} ]; then
-        touch {{ etcd_tmp_filename }}
         export ETCD_INITIAL_CLUSTER_STATE=new
         export ETCD_INITIAL_CLUSTER="
         {%- for host in groups[etcd_peers_group] -%}
@@ -160,6 +159,12 @@ start)
         quay.io/coreos/etcd:{{ etcd_version }}
     ;;

+    {% if etcd_init_cluster -%}
+    if [ ! -f {{ etcd_tmp_filename }} ]; then
+        touch {{ etcd_tmp_filename }}
+    fi
+    {% endif -%}
+
 stop)
     {% if run_as == "worker" -%}
     echo "==> no 'stop' action for proxy"
```

**Comment by mapuri** [comment] 2016-06-02 18:19
@vvb I think the above patch has similar limitation i.e. if etcd were to fail to start on first attempt then this will still go ahead  touch the file, right?

The latest ansible tries to mitigate this situation by also [checking for docker state](https://github.com/contiv/ansible/blob/master/roles/etcd/templates/etcd.j2#L132) before proceeding, and shall fix this particular issue too.

However it still doesn't fix everything and we need to think following two cases a bit more:
- single master clusters and;
- multi-master clusters with masters added incrementally

let's keep this issue open till we can come up with a good solution with the given constraints of etcd cluster formation.

**Comment by mapuri** [comment] 2016-06-07 16:56
closing this as #218 addresses the scenarios mentioned above.

**Closed as completed by mapuri** 2016-06-07 16:56 UTC
