### ISSUE TITLE
Restart failing on the secondary node in a baremetal swarm cluster 

### ISSUE THREAD

**Issue by apoorva11029** [contiv/ansible#256] opened 2016-07-26 18:58 UTC
Using:
sudo systemctl stop etcd
sudo systemctl start etcd
Error log:
● etcd.service - Etcd
   Loaded: loaded (/etc/systemd/system/etcd.service; static; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2016-07-26 11:54:30 PDT; 275ms ago
  Process: 1107 ExecStop=/usr/bin/etcd.sh stop (code=exited, status=1/FAILURE)
  Process: 914 ExecStart=/usr/bin/etcd.sh start (code=exited, status=1/FAILURE)
 Main PID: 914 (code=exited, status=1/FAILURE)

**Comment by gaurav-dalvi** [comment] 2016-07-26 19:02
This is happening when we have swarm cluster of 2 centos VMs and then during TestTriggerClusterStoreRestart this test we stop and start etcd on both nodes. We get this error especially on second node.

**Comment by mapuri** [comment] 2016-07-26 20:01
@apoorva11029 @gaurav-dalvi 

please provide the outputs of `journalctl -u etcd` and `journalctl -u docker` from the affected node.

**Comment by apoorva11029** [comment] 2016-07-26 22:32
PFA the two logs.

[docker_log.txt](https://github.com/contiv/ansible/files/384952/docker_log.txt)
[etcd_log.txt](https://github.com/contiv/ansible/files/384953/etcd_log.txt)

**Comment by mapuri** [comment] 2016-07-27 00:05
just debugged this with @apoorva11029 and @gaurav-dalvi .

Below are the findings and possible options:

@apoorva11029 @gaurav-dalvi , feel free to pick whichever option you would like to take and we can resolve this issue accordingly:

**Root cause:**
- etcd scripts use service-vip to simplify peer discovery (when a cluster dynamically grows and shrinks)
- however, net-demo-installer doesn't use a valid vip
- this causes etcd scripts to assume that there are no peers on the secondary node (in a two node setup) as the vip get's filtered (being a [special address](https://github.com/contiv/ansible/blob/master/roles/etcd/templates/etcd.j2#L79))

**Option 1:**
- use the `ucarp` role in the `netplugin_node` host group

_Pros:_
- this is congruent with how etcd scripts shall be used in a more dynamic setup. volplugin and cluster already use it this way

_Cons:_
- this will affect all the users of demo installer, which is meant to bring up more fixed environments.

**Option 2:**
- adjust system tests to validate etcd star/stop on primary node (actually, the node whose IP get's picked up as vip by the installer)

_Pros:_
- simple

_Cons:_
- will break again (when we forget about this in a few weeks and add another test ;-) )

**Option 3:** (this one is a quick thought, you may still need to verify)
- start a 3 node cluster instead of two

_Pros:_
- simple
- no need to worry about vip and doesn't affect other demo users

_Cons:_
- baremetal test setups will now need more hardware

**Comment by gaurav-dalvi** [comment] 2016-07-27 17:21
Thanks @mapuri for detailed explanation. 
I am more inclined towards Option 1 or 3. @shaleman : Any comments on this one ?

**Comment by gaurav-dalvi** [comment] 2016-07-27 18:32
@mapuri : We synced up with Sukhesh and Looks like going forward, we will be executing all systemtests on 3 node cluster. (Baremetal and Vagrant). 

@apoorva11029 : Could you please verify this one Baremetal as well as Vagrant after that we can close this issue.

**Comment by mapuri** [comment] 2016-08-10 23:50
closing this as I think `option 3` seems to be working fine for net-demo environments. 

Feel free to re-open or create another issue if the problem still exists.

**Closed as completed by mapuri** 2016-08-10 23:50 UTC
